#!/bin/sh
# Update cloud-init from proposed
#
# Copyright 2017 Canonical Ltd.
# Joshua Powers <josh.powers@canonical.com>

pkg="cloud-init"
fname="/etc/apt/sources.list.d/proposed.list"
mirror="http://us.archive.ubuntu.com/ubuntu/"
release=$(lsb_release -cs)
installed=$(dpkg-query -W -f='${Version}' $pkg)

fail() { [ $# -eq 0 ] || error "$@"; exit 1; }

echo "deb $mirror $release-proposed main" | sudo tee "$fname"
sudo apt-get update
sudo apt-get install cloud-init -y || fail "install from proposed failed"
sudo rm "$fname"
sudo apt-get update

echo "Package: $pkg"
echo "Original Version: $installed"
upgraded=$(dpkg-query -W -f='${Version}' $pkg)
echo "Upgraded Version: $upgraded"
