#!/usr/bin/env python
"""Parse a changelog into trello checklist markdown for SRUs."""

import argparse
import re


def get_parser():
   parser = argparse.ArgumentParser()
   parser.add_argument(
       '-c', '--changelog', required=True, help='Changelog file to parse')
   parser.add_argument(
       '-n', '--num-sections', required=False, default=1, type=int,
       dest='numSections',
       help='Number of changelog sections to parse. Default: 1.')
   parser.add_argument(
       '-p', '--project-name', required=False, default='cloud-init', type=str,
       dest='projectName',
       help='Changelog file to parse')
   parser.add_argument(
       '-a', '--all-changes', required=False, default=False,
       action='store_true', dest='allChanges',
       help=('Include all changes with the section. Default: limit entries to'
             ' those containing bugs.'))
   return parser


def main():
  parser = get_parser()
  args = parser.parse_args()
  with open(args.changelog, 'rb') as stream:
    content = stream.read()

  section_marker = '{projectName} ('.format(projectName=args.projectName)
  section_count = 0
  for item in content.split('- '):
    if section_marker in item:
        section_count += 1
        if section_count > args.numSections:
            break
        continue
    # strip all whitespace/newlines and truncate end of section committer
    changelog_item = ' '.join([i for i in item.split() if i != '-'])
    m = re.match(r'.*\(LP: #(?P<bugs>[\d ,#]+)\).*', changelog_item)
    if m:
        bugnums = m.group('bugs').split(', #')
        bug_prefix = ''.join([
            '[LP: #{bug}](http://pad.lv/{bug}) '.format(bug=bugnum)
            for bugnum in bugnums])
        # Strip bug details from end and put it as markdown in prefix
        summary = re.sub(r'\(LP:[^)]+\)', '', changelog_item)
        print(' - {0} {1}'.format(bug_prefix, summary))
    elif args.allChanges:
        print(' - {0}'.format(changelog_item))

if __name__ == '__main__':
    main()
