#!/bin/bash
# https://gist.github.com/smoser/6391b854e6a80475aac473bba4ef0310

VERBOSITY=0
ASSUME_YES=false
OFFLINE=false
TEMP_D=""
START_D="$PWD"
FORMATS=".tar.gz .tar.xz .tar.bz2"

MSG_BORDER_LINE="========================================"

cleanup(){
    [ ! -d "$TEMP_D" ] || rm -Rf "$TEMP_D";
    git worktree prune
}
error() { echo "$@" 1>&2; }
fail() { [ $# -eq 0 ] || error "$@"; exit 1; }

Usage() {
    cat <<EOF
Usage: ${0##*/} [ options ] <<ARGUMENTS>>

   build a package, put output in ../out

   options:
      --ref R         what to build from [default to current branch].
      --offline       perform no upstream orig.tar.gz downloads
    -o | --output D   put output in D. [default ../out]
EOF
}

bad_Usage() { Usage 1>&2; [ $# -eq 0 ] || error "$@"; return 1; }

prompt_yes_no() {
    [ "${ASSUME_YES}" = "true" ] && {
        error "assuming yes to prompt:" "$@"
        return 0
    }
    local resp
    echo -n "$@" "? (y/n)  "
    read resp || fail "failed to read user input"
    if [ "$resp" = "y" ]; then
       return 0
    fi
    return 1
}

debug() {
    local level=${1}; shift;
    [ "${level}" -gt "${VERBOSITY}" ] && return
    error "${@}"
}

find_orig() {
    local src="$1" ver="$2" dir="" n="" ext="" nver=""
    shift 2
    nver=$(no_epoch "$ver")
    for dir in "$@"; do
        for ext in $FORMATS; do
            n="${src}_${nver}.orig${ext}"
            [ -f "$dir/$n" ] && _RET="$dir/$n" &&
                echo "$dir/$n" && return 0
        done
    done
    return 1
}

# no_epoch(version): drop a leading epoch from a version
#   no_epoch(1:15.0+dfsg1-1ubuntu2.1) = 15.0+dfsg1-1ubuntu2.1
#   no_epoch("1.0") = "1.0"
no_epoch() {
    case "$1" in
        [0-9]:*|[0-9][0-9]:*) echo "${1#*:}";;
        *) echo "$1"
    esac
}

get_genchanges_version() {
    local pkg_name="$1" suite="$2" collapsed_args="$3" devel=""
    # if args already had a '-v' in it, then do nothing.
    _RET=""
    [ "${collapsed_args#* -v}" = "${collapsed_args}" ] ||
        { debug 1 "-v already present in args"; return 0; }
    devel=$(distro-info --devel)
    [ "$suite" = "$devel" ] &&
        { debug 1 "-v not relevant for devel suite ($suite)"; return 0; }
    [ "${suite^^}" = "UNRELEASED" ] &&
        { debug 1 "-v not relevant for unreleased"; return 0; }
    if ! command -v rmadison >/dev/null 2>&1; then
        debug 1 "rmadison not available."
        return 0
    fi
    local ga_suite="" ga_version="" updates_suite="" updates_version=""
    case "$suite" in
        *-proposed|*-updates)
            updates_suite=${suite%-*}-updates
            ga_suite=${suite%-*};;
        *)
            updates_suite="$suite-updates";
            ga_suite=${suite};;
    esac
    updates_version=$(
        rmadison --url=ubuntu --suite="${updates_suite}" $pkg_name |
        awk '-F|' '$4 ~ /source/ {gsub(/ /, ""); print $2}')
    ga_version=$(
        rmadison --url=ubuntu --suite="${ga_suite}" $pkg_name |
        awk '-F|' '$4 ~ /source/ {gsub(/ /, ""); print $2}')
    debug 1 "$pkg_name versions updates=${updates_version} ga=${ga_version}"
    if [ -n "$updates_version" ]; then
        _RET="-v${updates_version}"
    elif [ -n "$ga_version" ]; then
        _RET="-v${ga_version}"
    else
        error "Failed to get version info for $pkg_name in" \
            "$updates_suite or $ga_suite."
        return 1
    fi
}

get_orig_tarball() {
    local changelog_file="$1" dir="${2:-..}" offset="$3" verbose="$4"
    local tarball_fp
    if [ "$OFFLINE" = "true" ]; then
        error "Skipping download of orig.tar.gz due to --offline param"
        return 0
    fi
    if ! get-orig-tarball "${changelog_file}" "${dir}" ${offset:+--offset=${offset}} $verbose; then
        error "failed to get orig tarball for $pkg_name at $pkg_ver"
        return 1
    fi
    tarball_fp=$(find_orig "${pkg_name}" "${upstream_ver}" "${dir}")
    if [ -z "${tarball_fp}" ]; then
        error "did not get a tarball at $upstream_ver with get-orig-tarball"
        return 1
    elif [ ! -f "$tarball_fp" ]; then
        error "orig tarball not a file: $tarball_fp"
        return 1
    fi
    error ${MSG_BORDER_LINE}
    error " Using orig tarball in $tarball_fp"
    sha256sum "${orig_tarball_fp}"
    error ${MSG_BORDER_LINE}
    return 0
}


main() {
    local short_opts="ho:vy"
    local long_opts="help,offline,output:,offset:,ref:,yes,verbose"
    local getopt_out=""
    getopt_out=$(getopt --name "${0##*/}" \
        --options "${short_opts}" --long "${long_opts}" -- "$@") &&
        eval set -- "${getopt_out}" ||
        { bad_Usage; return; }

    local cur="" next="" out_d="../out" ref="" offset="0"

    while [ $# -ne 0 ]; do
        cur="$1"; next="$2";
        case "$cur" in
            -h|--help) Usage ; exit 0;;
               --offset) offset=$next; shift;;
            -o|--output) out_d=$next; shift;;
            --offline) OFFLINE=true;;
            -v|--verbose) VERBOSITY=$((${VERBOSITY}+1));;
            -y|--yes) ASSUME_YES=true;;
               --ref) ref=$next; shift;;
            --) shift; break;;
        esac
        shift;
    done

    if [ -z "$ref" ]; then
        cur_branch=$(git rev-parse --abbrev-ref HEAD) ||
            fail "failed to get current branch"
        ref="$cur_branch"
    fi

    TEMP_D=$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX") ||
        fail "failed to make tempdir"
    trap cleanup EXIT

    local wtd="${TEMP_D}/wtd" pkg_ver pkg_name upstream_ver upstream_hash
    local orig_tarball orig_tarball_fp
    git worktree add --force "$wtd" "$ref" ||
        fail "failed worktree add $wtd $ref"

    pkg_ver=$( cd "$wtd" && dpkg-parsechangelog --show-field Version) ||
        fail "failed reading package version"
    pkg_name=$(cd "$wtd" && dpkg-parsechangelog --show-field Source) ||
        fail "failed to read Source from changelog"
    suite=$(cd "$wtd" && dpkg-parsechangelog --show-field Distribution) ||
        fail "failed to read Distribution from changelog"

    upstream_ver=${pkg_ver%-*}

    # turn 0.7.7-10-gbc2c326-0ubuntu1 into 'bc2c326'
    upstream_hash=${upstream_ver##*-g}

    local native=false
    local dsf="debian/source/format"
    if [ -f "$wtd/$dsf" ]; then
        local fmt="" native3="3.0 (native)"
        read fmt < "$wtd/$dsf"
        case "$fmt" in
            "$native3"|*native*)
                debug 0 "package ${pkg_name} is native per $dsf"
                native=true;;
        esac
    fi
    if [ "$native" = "false" ]; then
        case "${pkg_ver}" in
            *-*) :;;
            *) debug 0 "package ${pkg_name} is native per version ${pkg_ver}"
                native=true;;
        esac
    fi

    if [ "$native" = "true" ]; then
        # rename this dir from 'wtd' to <pkg>-<ver> as the top level dir
        # gets used in the tarball.
        mv "$wtd" "${TEMP_D}/$pkg_name-$pkg_ver"
        wtd="${TEMP_D}/$pkg_name-$pkg_ver"
    else
        error "pkg_name=$pkg_name pkg_ver=$pkg_ver upstream_ver=$upstream_ver suite=$suite"
        local orig_tarball_fp="" orig_tarball_fp=""
        orig_tarball_fp=$(find_orig "${pkg_name}" "${upstream_ver}" .. ../dl)
        if [ -n "$orig_tarball_fp" ]; then
            tarball_dir=$(dirname "$orig_tarball_fp")
            if [ "${tarball_dir}" = "../dl" ]; then
                # Download and compare this tarball with latest upstream
                if ! get_orig_tarball debian/changelog ../dl "${offset}"; then
                    prompt_yes_no "No upstream tarball for ${upstream_ver}, " \
                        "should we create a new orig.tar.gz from the local " \
                        "branch" ||
                        fail "No upstream tarball found for ${upstream_ver}"
                fi
            fi
            if ! prompt_yes_no "Proceed with build-package"; then
                tar_dir=$(dirname "${orig_tarball_fp}")
                error "Canceled build-package."
                error "To replace orig.tar.gz with latest upstream:"
                error "  get-orig-tarball debian/changelog ${tar_dir} -v"
                exit 0
            fi
        elif [ -x tools/make-tarball ]; then
            if [ ! -d "../dl" ]; then
                mkdir ../dl ||
                   fail "failed to create ../dl from $PWD"
                error "created ../dl from $PWD for orig tarballs."
            fi
            orig_tarball="${pkg_name}_$(no_epoch "${upstream_ver}").orig.tar.gz"
            orig_tarball_fp="../dl/$orig_tarball"
            if prompt_yes_no "Check for an upstream cloud-init_${upstream_ver}.orig.tar.gz on which to base this debdiff"; then
                if ! get_orig_tarball debian/changelog ../dl "${offset}"; then
                   error ${MSG_BORDER_LINE}
                   error " No cloud-init_${upstream_ver}.orig.tar.gz found"
                   error "Creating $orig_tarball_fp using" \
                   "make-tarball --output=$orig_tarball_fp $upstream_hash"
                   error ${MSG_BORDER_LINE}
                   sleep 1
                   ./tools/make-tarball "--output=$orig_tarball_fp" "$upstream_hash" ||
                       fail "failed to make tarball"
                fi
            else
                sleep 1
                error ${MSG_BORDER_LINE}
                echo ./tools/make-tarball "--output=$orig_tarball_fp"
                ./tools/make-tarball "--output=$orig_tarball_fp" ||
                    fail "failed to make tarball"
                error ${MSG_BORDER_LINE}
            fi
        else
            if ! get_orig_tarball "" "${offset}" -v; then
                fail ""
            fi
        fi

        local ofp_name
        ofp_name=$(basename "$orig_tarball_fp")
        orig_tarball_fp=$(readlink -f "$orig_tarball_fp") ||
            fail "failed to get full path to $orig_tarball_fp"
        ln -s "$orig_tarball_fp" "$TEMP_D/${ofp_name}"
    fi

    if [ "$native" != "true" ]; then
        local debtar="${TEMP_D}/extra/debian.tar"
        mkdir "${TEMP_D}/extra" || fail "failed mkdir ${TEMP_D}/extra"

        # copy out debian dir.
        tar -C "$wtd" -cf "${TEMP_D}/extra/debian.tar" debian/ ||
            fail "failed to create tarball of debian."

        # clean wtd completely and create empty dir.
        rm -Rf "$wtd" ||
            fail "failed removing $wtd"
        mkdir "$wtd" ||
            fail "failed creating $wtd"

        # extract upstream tarball, remove it's debian dir, extract ours.
        tar -C "$wtd" --strip-components=1 -xf "${orig_tarball_fp}" ||
            fail "failed to extract $orig_tarball_fp in $wtd"
        if [ -d "$wtd/debian" ]; then
            debug 0 "Removing upstream's debian dir in favor of packaging."
            rm -Rf "$wtd/debian" ||
                fail "failed removing debian dir from upstream tarball."
        fi
        tar -C "$wtd" -xf "$debtar" ||
            fail "failed extracting debian tarball in wordir"
    else
        rm -Rf "$wtd/.git" || fail "failed removing .git dir"
    fi

    # try to magically add '-v' if its not present.
    local genchanges_v=""
    get_genchanges_version "$pkg_name" "$suite" " $* " ||
        fail "Failed to get genchanges version for $pkg_name $suite ' $* '"
    genchanges_v="$_RET"

    if [ $# -eq 0 ]; then
        set -- -d -S -nc ${genchanges_v}
    elif [ -n "${genchanges_v}" ]; then
        set -- "$@" ${genchanges_v}
    fi

    debug 0 "building with:" "$@"
    ( cd "$wtd" && debuild "$@" ) || fail "FAILED: debuild $*"

    ( for f in "$TEMP_D/"*; do echo "$f"; done )

    mkdir -p "$out_d"
    for f in "${TEMP_D}/"*; do
        [ -f "$f" ] || continue
        cp "$f" "$out_d/" && echo "wrote ${out_d}/${f##*/}" ||
            fail "failed to copy $f to $out_d"
    done
    return 0
}

main "$@"
# vi: ts=4 expandtab
