#!/bin/bash

if [ $# != 2 ]; then
 echo "usage: $0 <RELEASE_MAJOR.MINOR> <PREVIOUS_MAJOR_MINOR>"
 exit 1
fi

RELEASE_MAJOR_MINOR=$1
PREVIOUS_MAJOR_MINOR=$2

RELEASE_TIME_SPAN=`git log $PREVIOUS_MAJOR_MINOR..HEAD --pretty="%ar" | tail -n 1`

if [ ! -e ChangeLog ]; then
  echo "Please run this script from the root directory of cloud-init source tree"
  exit 1
fi

if [ "main" != "$(git branch --show-current)" ]; then
  echo "Changing branch to main and git pull latest upstream (y/n) ?"
  read RESP
  if [ "$RESP" != "y" ]; then
     echo "Please first change to main branch and pull upstream commits"
     exit 1
  fi
  git checkout main
fi
git pull


RELEASE_TIME_SPAN=${RELEASE_TIME_SPAN/ ago/}
NUM_CONTRIBUTORS=$(git log "$PREVIOUS_MAJOR_MINOR"..HEAD --pretty="%aN" | sort -u | wc -l)
NUM_GITHUB_BUGS=$(git log "$PREVIOUS_MAJOR_MINOR"..HEAD | grep -c "Fixes GH")
NUM_LAUNCHPAD_BUGS=$(git log "$PREVIOUS_MAJOR_MINOR"..HEAD | grep -c "LP: #")
NUM_TOTAL_BUGS=$((NUM_GITHUB_BUGS + NUM_LAUNCHPAD_BUGS))
CHANGELOG=$(git log "$PREVIOUS_MAJOR_MINOR"..HEAD | log2dch |  sed 's/^   //g')

echo "The release notes will be printed to this console."
echo "Continue?"
read

cat << EOF
Summary: Release $RELEASE_MAJOR_MINOR
"Further information:"
== Release Notes ==

Cloud-init release $RELEASE_MAJOR_MINOR is now available

The $RELEASE_MAJOR_MINOR release:
 * spanned about $RELEASE_TIME_SPAN
 * had $NUM_CONTRIBUTORS contributors
 * fixed $NUM_TOTAL_BUGS issues

Highlights:
  <TODO_SUMMARIZED_HIGHLIGHTS>

== Changelog ==
$CHANGELOG
EOF

echo "Refresh main and create a new release branch? (y/n)"
read RESP
if [ "$RESP" = "y" ]; then
  git checkout main
  git pull
  git checkout -b upstream/$RELEASE_MAJOR_MINOR
  printf "%s\n%s\n\n%s\n" "$RELEASE_MAJOR_MINOR" "$CHANGELOG" "$(cat ChangeLog)" > ChangeLog
  sed -i "s/${PREVIOUS_MAJOR_MINOR}[.0-9]*/$RELEASE_MAJOR_MINOR/" meson.build
  git diff
  cat > commit.msg <<EOF
Release $RELEASE_MAJOR_MINOR

Bump the version in meson.build to $RELEASE_MAJOR_MINOR and update ChangeLog.
EOF

  git commit -a -F commit.msg
fi

cat <<EOF
 Create the merge proposal from your upstream/$RELEASE_MAJOR_MINOR branch
EOF
